name: Run missing-license action

on:
  workflow_dispatch:
  

jobs:
  missing-license:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: alan-turing-institute/missing-license@main
        with:
          organization: alan-turing-institute
          app_id: ${{ secrets.APP_ID }}
          dry_run: "false"
          app_private_key: ${{ secrets.APP_PRIVATE_KEY }}
          app_installation_id: ${{ secrets.APP_INSTALLATION_ID }}
          issue_body_path: ./missing-license-issue-template.md
